---
haproxy_app_name: myapp
haproxy_mode: http
haproxy_enable_stats: enable 
haproxy_algorithm: roundrobin
haproxy_backend_servers:
  - {name: server1, ip: 192.168.33.11, port: 80, paramstring: cookie A check}
  - {name: server2, ip: 10.0.2.15, port: 80, paramstring: cookie A check}
haproxy_stats_users:
  - {username: joe, password: soap}
