---
name: playbook
description: run playbook
runner_type: local-shell-cmd
entry_point: ""
enabled: true
parameters:
  sudo:
    immutable: true
    default: true
  kwarg_op:
    immutable: true
  timeout:
    default: 6000
  cmd:
    description: "Command to run"
    immutable: true
    default: "/usr/local/bin/playbook {{host}} {{role}}"
  role:
    description: "role"
    type: string
    required: true
  host:
    description: "host"
    type: string
    required: true
