---
name: run-playbook
description: run run-playbook
runner_type: local-shell-cmd
entry_point: ""
enabled: true
parameters:
  sudo:
    immutable: true
    default: true
  kwarg_op:
    immutable: true
  timeout:
    default: 6000
  cmd:
    description: "Command to run"
    immutable: true
    default: "/usr/local/bin/run-playbook {{commandoption}}  {{vcenter}}"
  vcenter:
    description: "Vsphere vcenter"
    type: string
    required: true
  commandoption:
    description: "plan or apply"
    type: string
    required: true
