---
name: run-playbook
description: run run-playbook
runner_type: local-shell-cmd
entry_point: ""
enabled: true
parameters:
  sudo:
    immutable: true
    default: true
  kwarg_op:
    immutable: true
  timeout:
    default: 6000
  cmd:
    description: "Command to run"
    immutable: true
    default: "/usr/local/bin/run-playbook {{playbook-host}}  {{playbook-tag}}"
  playbook-tag:
    description: " playbook-tag"
    type: string
    required: true
  playbook-host:
    description: "host"
    type: string
    required: true
