---
- hosts: 127.0.0.1
  gather_facts: no
  connection: local
  tasks:

    - name: Clone itservice
      git:
        repo: git@git.zooxlabs.com:zooxco/itservice.git
        version: master
        dest: /opt/stackstorm/packs/st2_chatops_aliases/playbooks/itservice
        accept_hostkey: yes

    - name: Running Terraform {{ command }}
      shell: |
        git-crypt unlock ~/.fos-gridvcenter01/terraform-vsphere.pem
        terraform init -var-file=~/.fos-gridvcenter01/terraform.tfvars
        terraform {{ command }} -var-file=~/.fos-gridvcenter01/terraform.tfvars
      register: command_result
      args:
        chdir: "/opt/stackstorm/packs/st2_chatops_aliases/playbooks/itservice/terraform-vsphere/fos-gridvcenter01/lib"

    - debug: msg="{{ command_result.stdout }}"
