---
- hosts: 127.0.0.1
  gather_facts: no
  connection: local
  tasks:

    - name: Running Terraform plan fos-gridvcenter01
      shell: |
        echo user1 >> /tmp/user1
      register: output_plan_fos_gridvcenter01
      args:
        chdir: "~/git/itservice/terraform-vsphere/fos-gridvcenter01/lib"
      tags:
        - fos-gridvcenter01
      when: commandoption == "plan"

    - debug: msg="{{ output_plan_fos_gridvcenter01.stdout }}"
      tags:
        - fos-gridvcenter01
      when: commandoption == "plan"

