---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - { role: haproxy,
        tags: haproxy }
    - { role: keepalived,
        tags: keepalived }
    - { role: pbis,
        tags: pbis }
  tasks:
    - copy:
        src: /home/stanley/git/itservice/terraform-vsphere/Bootstrap/postinstall.sh
        dest: /tmp/postinstall.sh
        mode: 0755
      tags:
        - linux
    - copy:
        src: /home/stanley/git/itservice/terraform-vsphere/Bootstrap/storage_map.csv
        dest: /tmp/storage_map.csv
      tags:
        - linux

    - name: Run postinstall
      become: yes
      become_user: root
      become_method: sudo
      shell: "/tmp/postinstall.sh"
      tags:
        - linux

    - name: clean /tmp
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/postinstall.sh
        - /tmp/storage_map.csv
        - /tmp/fdisktmp
      tags:
        - linux

    - name: Copy storage_map.csv
      win_copy: src=/home/stanley/git/itservice/terraform-vsphere/Bootstrap/storage_map.csv dest=c:\storage_map.csv
      tags:
        - windows

    - name: Copy postinstall_win.ps1
      win_copy: src=/home/stanley/git/itservice/terraform-vsphere/Bootstrap/postinstall_win.ps1 dest=c:\postinstall_win.ps1
      tags:
        - windows

    - name: Run postinstall_win.ps1
      win_command: powershell.exe -ExecutionPolicy ByPass -File C:/postinstall_win.ps1
      register: postinstall_win
      tags:
        - windows

    - debug: msg="{{ postinstall_win.stdout }}"
      tags:
        - windows

    - name: Run id svc-terraform
      shell: id svc-terraform
      register: svc_terraform
      tags:
        - pbis

    - debug: msg="{{ svc_terraform.stdout }}"
      tags:
        - pbis
