---
- hosts: 127.0.0.1
  gather_facts: no
  connection: local
  tasks:

    - name: Clone itservice
      git:
        repo: git@git.zooxlabs.com:zooxco/itservice.git
        version: master
        dest: /opt/stackstorm/packs/st2_chatops_aliases/playbooks/itservice
        accept_hostkey: yes
      tags:
        - fos-gridvcenter01
        - fos-vcenter01

    - name: Running Terraform fos-gridvcenter01
      shell: |
        git-crypt unlock ~/.fos-gridvcenter01/terraform-vsphere.pem
        terraform init -var-file=~/.fos-gridvcenter01/terraform.tfvars
        terraform {{ package }} -var-file=~/.fos-gridvcenter01/terraform.tfvars
      register: command_result
      args:
        chdir: "/opt/stackstorm/packs/st2_chatops_aliases/playbooks/itservice/terraform-vsphere/fos-gridvcenter01/lib"
      tags:
        - fos-gridvcenter01

    - debug: msg="{{ command_result.stdout }}"
      tags:
        - fos-gridvcenter01

    - name: Running Terraform fos-vcenter01
      shell: |
        git-crypt unlock ~/.fos-vcenter01/terraform-vsphere.pem
        terraform init -var-file=~/.fos-vcenter01/terraform.tfvars
        terraform {{ package }} -var-file=~/.fos-vcenter01/terraform.tfvars
      register: command_result
      args:
        chdir: "/opt/stackstorm/packs/st2_chatops_aliases/playbooks/itservice/terraform-vsphere/fos-vcenter01/lib"
      tags:
        - fos-vcenter01

    - debug: msg="{{ command_result.stdout }}"
      tags:
        - fos-vcenter01
