---
- hosts: 127.0.0.1
  gather_facts: no
  connection: local
  tasks:

    - name: Clone itservice
      git:
        repo: git@git.zooxlabs.com:zooxco/itservice.git
        version: master
        dest: ~/git/itservice
        accept_hostkey: yes
      tags:
        - git-clone

    - name: pull from git
      git:
        repo: git@git.zooxlabs.com:zooxco/itservice.git
        dest: ~/git/itservice
        update: yes
        version: master
      tags:
        - git-pull
        - fos-gridvcenter01
        - fos-vcenter01

    - name: unlock state file
      shell: |
        git-crypt unlock ~/.keys/terraform-vsphere.pem
      register: output_result
      args:
        chdir: "~/git/itservice/terraform-vsphere"
      tags:
        - git-clone


    - name: Running Terraform plan fos-gridvcenter01
      shell: |
        terraform init -var-file=~/.fos-gridvcenter01/terraform.tfvars
        terraform plan -var-file=~/.fos-gridvcenter01/terraform.tfvars
      register: output_result
      args:
        chdir: "~/git/itservice/terraform-vsphere/fos-gridvcenter01/lib"
      tags:
        - fos-gridvcenter01
      when: commandoption == "plan"

    - name: Running Terraform apply fos-gridvcenter01
      shell: |
        terraform init -var-file=~/.fos-gridvcenter01/terraform.tfvars
        terraform apply -var-file=~/.fos-gridvcenter01/terraform.tfvars -auto-approve
      register: output_result
      args:
        chdir: "~/git/itservice/terraform-vsphere/fos-gridvcenter01/lib"
      tags:
        - fos-gridvcenter01
      when: commandoption == "apply"

    - debug: msg="{{ output_result.stdout }}"
      tags:
        - fos-gridvcenter01

    - name: Running Terraform plan fos-vcenter01
      shell: |
        terraform init -var-file=~/.fos-vcenter01/terraform.tfvars
        terraform plan -var-file=~/.fos-vcenter01/terraform.tfvars
      register: output_result
      args:
        chdir: "~/git/itservice/terraform-vsphere/fos-vcenter01/lib"
      tags:
        - fos-vcenter01
      when: commandoption == "plan"

    - name: Running Terraform apply fos-vcenter01
      shell: |
        terraform init -var-file=~/.fos-vcenter01/terraform.tfvars
        terraform apply -var-file=~/.fos-vcenter01/terraform.tfvars -auto-approve
      register: output_result
      args:
        chdir: "~/git/itservice/terraform-vsphere/fos-vcenter01/lib"
      tags:
        - fos-vcenter01
      when: commandoption == "apply"

    - debug: msg="{{ output_result.stdout }}"
      tags:
        - fos-vcenter01
